[URL]
User_Name = 鄢桀蚀荼-YanjerTS
User_CALL = 御主人様
User_B_UID = 1979641484
User_B_LiveRoom = 24459881|
#用|区分每个房间号 最后通过push到array中 然后length决定显示几个按钮
Login_BiliBili = https://passport.bilibili.com/login
#Main中的需要依赖Login后的cookie访问
Main_Live = 'https://link.bilibili.com/p/center/index#/my-room/start-live'#为了防止#被理解为注释 用引号表示 对于没有#的不加无所谓
Main_Creator = https://member.bilibili.com/platform/home
Main_Post = https://member.bilibili.com/platform/upload/video/frame
Main_Space = https://t.bilibili.com/
Main_Message = https://message.bilibili.com/
#Personal中需要设置UID
Personal_Favourite = https://space.bilibili.com/{uid}/favlist
Personal_Space = https://space.bilibili.com/{uid}
#房间号单独设置
Live_Room = https://live.bilibili.com/{room_id}
Live_Home = https://live.bilibili.com/

